### ISSUE TITLE
Polymorphic List Type

### ISSUE THREAD

**Issue by ryangittings** [gittingsstudio/pages-cms#5]
Support for this sort of config:

```
content:
  - name: pages
    label: Pages
    path: src
    type: collection
    filename: "{primary}/index.md"
    exclude: []
    filters:
      - name: layout
        value: layouts/page.njk
    fields:
      - name: layout
        type: string
        hidden: true
        default: layouts/page.njk
      - name: title
        type: string
        label: Title
      - name: blocks
        list: true
        label: Blocks
        type: object
        types:
          - name: hero
            label: Hero
            type: object
            fields:
              - name: eyebrow
                type: string
                label: Eyebrow
                required: false
              - name: title
                type: string
                label: Title
              - name: content
                type: markdown
                label: Content
              - name: button
                type: object
                label: Button
                fields:
                  - name: text
                    type: string
                    label: Text
                    required: false
                  - name: link
                    type: string
                    label: Link
                    required: false
          - name: text
            label: Text
            type: object
            fields:
              - name: eyebrow
                type: string
                label: Eyebrow
                required: false
              - name: title
                type: string
                label: Title
              - name: content
                type: markdown
                label: Content
```
